travis:
  secure:
    BINSTAR_TOKEN: qhvcLuj7Xdmwp/WNxWzlOvXGmob6O2RrpLlyZ5kbtf3ovAOq1ppuaI7QztWMR2QNpOgeykSf6bpAJWvs9JUSpomk1MbuYj4tJFZSDlM4B82tDYpKyQFP88UZLuGU2dZvs+7f52QAew9LklInvTHnh/anKLl+yU5q1b6ubrzLny0xDwQUSdzBSCr0XanZRukeyl+Lh78OGKDYNJDAxLz2A1kRfouSrVvt8/rlGBw12JlN1rqrFBVafnURoLoIUeeN0FEB7oDKg1TBmQJudD6mRWyde3UWtTdwC6K82DdAkcTWIKO/EbccH4XEs+jXWKvga2o/sFhT8euFRys+KlJ2H5fzetzEZTEYxTuWCNqs/mFn+ES6d98ta8KKGghJYkY+AEr6NJkcTvIgJl7awTBqA1J7CHZayXXubGS/9CGgDo/1LzjXfd7kq0LT+ZyJmbuMgEXzfSk+nBLpIdKKTJuw3x7taXLOkUeUCDvP5S8c/fTQUHVV07zryEOP5RCpuTmQWV44vqmean5Yvkhy6h2h3Kac9iVURa+8YZq8AI1636sHDF/yfIROZtEsJbySXM3peVKk0FIbnbBj4HxHF8bGTmNSPyYS/hcCppLNe8VXHDp6qbhs6roizmu1mOwAJ+9gqOlxjvC3Iz3PTU9JLihhfl8OV0OqsNlk5IdR2fixcX0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
